version: "3"

services:
  application:
    build: ./application
    environment:
      - LOCALE=id_ID
      - TZ=Asia/Jakarta
    volumes:
      - ../www:/var/www
    tty: true
  nginx:
    build: ./nginx
    environment:
      - PHP_FPM_HOST=application
      - PHP_FPM_PORT=9000
    volumes:
      - ../www:/var/www
    ports:
      - 80:80
    depends_on:
      - application
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=James
      - MYSQL_USER=wico
      - MYSQL_PASSWORD=James
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./mysql_data:/var/lib/mysql/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=James
    ports:
      - 8080:80
    links:
      - mysql:db
