version: "3"

services:
  application:
    build: ./application
    environment:
      - LOCALE=id_ID
      - TZ=Asia/Jakarta
    volumes:
      - /w/www:/var/www
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - mysql
    tty: true
  nginx:
    build: ./nginx
    environment:
      - PHP_FPM_HOST=application
      - PHP_FPM_PORT=9000
    volumes:
      - /w/www:/var/www
    ports:
      - 80:80
      - 7890:7890
    depends_on:
      - application
  mysql:
    image: mysql:5.7
    restart: always
    command: "--innodb_use_native_aio=0"
    environment:
      - MYSQL_ROOT_PASSWORD=James
      - MYSQL_USER=wico
      - MYSQL_PASSWORD=James
      - MYSQL_TCP_PORT=3306
    volumes:
      - /w/docker/mysql_data:/var/lib/mysql/
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=James
      - PMA_HOST=mysql
    ports:
      - 8080:80
    links:
      - mysql:db
    depends_on:
      - mysql
  redis:
    image: redis
    ports:
      - 6379:6379
